# -*- yaml -*-
minimum_pre_commit_version: "3.5.0"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: [--fix, --config=ruff.toml]
      - id: ruff-format
        args: [--fix, --config=ruff.toml]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - "--profile=black"
          - "--line-length=79"
          - "--filter-files"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
